resource.AddFile("models/weapons/dildo.mdl")
resource.AddFile("models/weapons/Dildo.phy")
resource.AddFile("models/weapons/Dildo.dx80.vtx")
resource.AddFile("models/weapons/Dildo.dx90.vtx")
resource.AddFile("models/weapons/Dildo.sw.vtx")
resource.AddFile("models/weapons/dildo.vvd")

resource.AddFile("models/weapons/dildo2.mdl")
resource.AddFile("models/weapons/Dildo2.phy")
resource.AddFile("models/weapons/Dildo2.dx80.vtx")
resource.AddFile("models/weapons/Dildo2.dx90.vtx")
resource.AddFile("models/weapons/Dildo2.sw.vtx")
resource.AddFile("models/weapons/dildo2.vvd")

resource.AddFile("settings/spawnlist/Dildooo.txt")